apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-backend
  namespace: backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: spring-api
  template:
    metadata:
      labels:
        app: spring-api
    spec:
      containers:
      - name: spring-app
        image: "vikt0rinho/backend:1e22a2ac16a70b1b7bcdc73a1b9e55e8f372d2df"
        ports:
        - containerPort: 8080
        env:
        - name: DB_URL
          value: "jdbc:postgresql://postgres-service.database.svc.cluster.local:5432/mydb"
        - name: DB_PASSWORD
          value: ""