apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-ui
  namespace: frontend
spec:
  replicas: 3
  selector: 
    matchLabels:
      app: frontend 
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: web-ui
<<<<<<< HEAD
        image: "vikt0rinho/frontend:d6d2b2e1bed859afe7c38895cf99ffb90cf9ed81"
>>>>>>> b521455 (trying to update images via git hub container registry)
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: frontend
spec:
  selector:
    app: frontend
  ports:
  - port: 80
    targetPort: 80
  type: ClusterIP