apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-ui
  namespace: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: web-ui
        image: "vikt0rinho/frontend:1e22a2ac16a70b1b7bcdc73a1b9e55e8f372d2df"
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: frontend
spec:
  selector:
    app: frontend
  ports:
  - port: 80
    targetPort: 80
  type: ClusterIP