apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: backend
type: Opaque
stringData:
  DB_PASSWORD: "password"
  MAIL_PASSWORD: "yrxr atjb sthm nouk"
  TEST_MAIL_PASSWORD: "583edf5f2bedc7"
  JWT_PASSWORD: "thisIsMysecregtfrdesww233eggtffeeddgkjjhhtdhttebd54ndhdhfhhhshs8877465sbbdd"
---
apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: database
type: Opaque
stringData:
  password: "password"